### ISSUE TITLE
504 Gateway Errors

### ISSUE THREAD

**Issue by palewire** [edsu/linkypedia#1]
Getting a lot of this when I try to crawl.

  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 504: Gateway Time-out

**Comment by edsu** [comment]
Yeah, I guess I should put a try/except around that ; I have seen them every few days as well.

**Comment by edsu** [comment]
Ok just pushed some changes to try to handly 504 errors by retrying a few times. Let me know how it works out.
